"""Regenerate config/tickers.txt from the live S&P 500 + Nasdaq-100 lists,
merged with anything pinned in config/extra_tickers.txt.

Run manually:      python -m scripts.update_universe
Run automatically: .github/workflows/update_universe.yml (weekly)
"""
from pathlib import Path

from bot.universe import build_universe

CONFIG_DIR = Path(__file__).resolve().parent.parent / "config"
TICKERS_FILE = CONFIG_DIR / "tickers.txt"
EXTRA_FILE = CONFIG_DIR / "extra_tickers.txt"

HEADER = """# Auto-generated by scripts/update_universe.py -- edits here get
# overwritten on the next refresh. To pin extra symbols permanently
# (e.g. something not in the S&P 500 / Nasdaq-100), add them to
# config/extra_tickers.txt instead -- those are merged back in every time.
#
# Source: S&P 500 + Nasdaq-100 (Wikipedia), deduplicated, refreshed weekly.
"""


def _read_symbol_list(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [
        line.strip().upper()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def main() -> None:
    universe = build_universe()
    if not universe:
        print("[update_universe] fetch failed, leaving existing tickers.txt untouched")
        return

    extra = _read_symbol_list(EXTRA_FILE)
    all_tickers = sorted(set(universe) | set(extra))

    TICKERS_FILE.write_text(HEADER + "\n".join(all_tickers) + "\n", encoding="utf-8")
    print(f"[update_universe] wrote {len(all_tickers)} tickers "
          f"({len(universe)} from S&P500/Nasdaq100 + {len(extra)} pinned extras) "
          f"to {TICKERS_FILE}")


if __name__ == "__main__":
    main()
